export const IPC_CHANNELS = {
  settingsGet: 'settings.get',
  settingsUpdate: 'settings.update',
  captureCommand: 'capture.command',
  captureEvent: 'capture.event',
  captureReady: 'capture.ready',
  speechListProfiles: 'speech.listProfiles',
  speechTestProfile: 'speech.testProfile',
  sessionGetRuntime: 'session.getRuntime',
  sessionPrewarm: 'session.prewarm',
  sessionStartPtt: 'session.startPtt',
  sessionStopPtt: 'session.stopPtt',
  sessionStartMeeting: 'session.startMeeting',
  sessionStopMeeting: 'session.stopMeeting',
  sessionCopyLiveSession: 'session.copyLiveSession',
  sessionExportLiveSession: 'session.exportLiveSession',
  historyList: 'history.list',
  historySearch: 'history.search',
  historyGet: 'history.get',
  historyDelete: 'history.delete',
  historyExport: 'history.export',
  diagnosticsExport: 'diagnostics.export',
  runtimeSnapshot: 'runtime.snapshot',
  runtimeNotification: 'runtime.notification',
  settingsChanged: 'settings.changed'
} as const
